channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy=1.20.1
  - matplotlib=3.3.4
  - pandas=1.2.2
  - geopandas=0.9.0
  - pytz=2020.1
  - scikit-image[version='>0.16.0']
  - scikit-learn=0.20.3
  - astropy=4.2
  - gdal=3.0.4
  - shapely=1.7.1
  - scipy=1.2.1
  - pyproj[version='>2.2.0']
  - pykrige=1.4.0
  - cartopy=0.17.0
  - pyfftw=0.12.0
  - rasterio=1.1.5
  - arosics=1.2.6
  - notebook
  - spyder
